services:
  db:
    image: postgres:15
    container_name: gsi360_db
    restart: always
    environment:
      POSTGRES_DB: gsi360_teste
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: Senhaforte123!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: gsi360-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
