# Generated by Django 5.1.7 on 2025-04-02 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='companies.companygroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompanyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_set', models.ManyToManyField(related_name='user_permissions', to='companies.operationalcompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
